version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Allow up to 10 open pull requests at any time
    open-pull-requests-limit: 10
    # Assign someone to review the PRs
    # assignees:
    #   - "Ghvinerias"
    # Add labels to the PRs
    labels:
      - "dependencies"
      - "automated"
