name: Manually Generate PDF

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate_cv:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PDF
        env:
          PDF_API_KEY: ${{ secrets.CONVERTAPI_TOKEN }}
        run: |
          wget -O web-to-pdf "https://raw.githubusercontent.com/Ghvinerias/learning-golang/refs/heads/main/web-to-pdf/build/linux/web-to-pdf"
          chmod +x ./web-to-pdf
          ./web-to-pdf https://ghvinerias.github.io/online-cv/print
        
      - name: Create assets directory
        run: mkdir -p assets/pdf

      - name: Move PDF to assets directory
        run: mv temp.pdf assets/pdf/Aleksandre-Ghvineria-CV-EN.pdf

      - name: cleanup
        run: rm -rf ./web-to-pdf

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git commit -m "Add generated CV"
          git push
