name: generate CV

on:
  workflow_dispatch:

jobs:
  generate_cv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PDF
        env:
          PDF_API_KEY: ${{ secrets.PDF_API_KEY }}
        # run: rm -rf assets/pdf/
        run: wget -O Aleksandre-Ghvineria-CV-EN.pdf "http://api.pdflayer.com/api/convert?access_key=${PDF_API_KEY}&document_url=https://ghvinerias.github.io/online-cv/print"

      - name: Create assets directory
        run: mkdir -p assets/pdf

      - name: Move PDF to assets directory
        run: mv Aleksandre-Ghvineria-CV-EN.pdf assets/pdf/

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git commit -m "Add generated CV"
          git push
