name: Manually Generate PDF

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate_cv:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PDF
        env:
          PDF_API_KEY: ${{ secrets.PDF_API_KEY_NEW }}
        run: |
              apt install jq
              # response=$(curl -s -X POST https://v2.convertapi.com/convert/web/to/pdf -H "Authorization: Bearer ${PDF_API_KEY_NEW}" -F "Url=https://ghvinerias.github.io/online-cv/print" -F "StoreFile=true" -F "FileName=Aleksandre-Ghvineria-CV-EN")
              # pdf_url=$(echo "$response" | jq -r '.Files[0].Url')
              # curl -o Aleksandre-Ghvineria-CV-EN.pdf "$pdf_url"

      # - name: Create assets directory
      #   run: mkdir -p assets/pdf

      # - name: Move PDF to assets directory
      #   run: mv Aleksandre-Ghvineria-CV-EN1.pdf assets/pdf/

      # - name: Commit and push changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add assets/
      #     git commit -m "Add generated CV"
      #     git push
